import { InsertCategory } from "@shared/schema";

export const defaultCategories: Omit<InsertCategory, 'createdAt'>[] = [
  {
    name: "Casa Rosada",
    slug: "casa-rosada",
    description: "Noticias del Poder Ejecutivo, Presidencia y Gabinete Nacional",
    color: "#6CACE4",
    icon: "Building2",
    priority: 100,
    isFeatured: true,
  },
  {
    name: "Congreso",
    slug: "congreso",
    description: "Actividad legislativa, Senado, Diputados y proyectos de ley",
    color: "#F6B40E",
    icon: "Landmark",
    priority: 90,
    isFeatured: true,
  },
  {
    name: "Justicia",
    slug: "justicia",
    description: "Poder Judicial, Corte Suprema, causas judiciales y fallos",
    color: "#8B4513",
    icon: "Scale",
    priority: 85,
    isFeatured: true,
  },
  {
    name: "Economía",
    slug: "economia",
    description: "Política económica, mercados, dólar, inflación y finanzas públicas",
    color: "#22C55E",
    icon: "TrendingUp",
    priority: 95,
    isFeatured: true,
  },
  {
    name: "Provincias",
    slug: "provincias",
    description: "Política provincial, gobernadores y legislaturas",
    color: "#3B82F6",
    icon: "Map",
    priority: 70,
    isFeatured: false,
  },
  {
    name: "Municipios",
    slug: "municipios",
    description: "Intendentes, concejos deliberantes y política municipal",
    color: "#8B5CF6",
    icon: "Building",
    priority: 60,
    isFeatured: false,
  },
  {
    name: "Internacional",
    slug: "internacional",
    description: "Relaciones exteriores, diplomacia y política global",
    color: "#06B6D4",
    icon: "Globe",
    priority: 75,
    isFeatured: true,
  },
  {
    name: "Seguridad",
    slug: "seguridad",
    description: "Fuerzas de seguridad, defensa y políticas de seguridad pública",
    color: "#EF4444",
    icon: "Shield",
    priority: 80,
    isFeatured: false,
  },
  {
    name: "Energía",
    slug: "energia",
    description: "Política energética, Vaca Muerta, renovables y tarifas",
    color: "#F59E0B",
    icon: "Zap",
    priority: 65,
    isFeatured: false,
  },
  {
    name: "Educación",
    slug: "educacion",
    description: "Política educativa, universidades y sistema educativo",
    color: "#10B981",
    icon: "GraduationCap",
    priority: 55,
    isFeatured: false,
  },
  {
    name: "Opinión",
    slug: "opinion",
    description: "Columnas de opinión, análisis editorial y perspectivas",
    color: "#A855F7",
    icon: "MessageSquare",
    priority: 50,
    isFeatured: false,
  },
  {
    name: "Datos y Visualizaciones",
    slug: "datos-visualizaciones",
    description: "Periodismo de datos, infografías y análisis cuantitativo",
    color: "#EC4899",
    icon: "BarChart3",
    priority: 45,
    isFeatured: false,
  },
];
